### ISSUE TITLE
HTTP Error 403: Target service not allowed

### ISSUE THREAD

**Issue by pbabbicola** [eywalker/nvidia-docker-compose#27]
I'm trying to run nvidia-docker-compose by running `nvidia-docker-compose up`. The docker-compose.yml is not the problem and nvidia-docker is working fine. I have latest docker and docker-compose, and nvidia-docker v1 (not 2)

I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/globant/.local/bin/nvidia-docker-compose", line 55, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Target service not allowed
```

What is the problem here? I tried also running as root.

**Comment by ghost** [comment]
@pbabbicola Running into the same issue, any chance you found a resolution?

**Comment by pbabbicola** [comment]
No, unfortunately I've been unable to. We ended up using nvidia-docker by itself.

**Comment by eywalker** [comment]
@pbabbicola @Ixalion I know this was couple months ago but I now have some time to work through issues on `nvidia-docker-compose`. If you can still reproduce the issue, could you let me know what you get if you just run `curl http://localhost:3476/docker/cli/json`?
