### ISSUE TITLE
I cannot access to nvidia_docker_host

### ISSUE THREAD

**Issue by MessyPaste** [eywalker/nvidia-docker-compose#30]
When I was running this command"nvidia-docker-compose",the terminal shows the following:

Traceback (most recent call last):
  File "/usr/local/bin/nvidia-docker-compose", line 55, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>

I have alreadly installed nvidia-docker and I can run nvidia-smi properly.I really cannot figure out what the problem is.Thank you for your answering!

**Comment by eywalker** [comment]
@LiuTaw Can you check what version of `nvidia-docker` you have installed? You can check this by running `nvidia-docker version`. If you have version 2, then `nvidia-docker-compose` is currently incompatible with `nvidia-docker` 2.

**Comment by MessyPaste** [comment]
Thank you for your reply.My nvidia-docker version is 2.0.3 that is incompatile with nvidia-docker-compose.I check the lastest doc in nvidia-docker and I found the lastest version is 2.0 and 1.0 is deprecated.That is to say,I cannot use nvidia-docker and nvidia-docker-compose combinely.Is my understanding right?Thanks a lot!
