### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 111] Connection refused> HELP ME!!! when running this command: sudo nvidia-docker-compose up --build

### ISSUE THREAD

**Issue by Student201562** [eywalker/nvidia-docker-compose#31]
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nvidia-docker-compose", line 55, in <module>
    resp = request.urlopen('http://{0}/docker/cli/json'.format(args.nvidia_docker_host)).read().decode()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by monitor1379** [comment]
Same issue to me, have you find anyway to temporarily fix this?

**Comment by SubmitCode** [comment]
I have exactly the same problem but I don't know why. Anyone can help?

**Comment by TommeyChang** [comment]
I have the problem, too.

**Comment by Kongsea** [comment]
exactly the same error as you. Is there anyone help to fix it?

**Comment by arthur-tacca** [comment]
This error means that it could not connect to the nvidia-docker plugin. There are a few possible reasons for this, but the most likely two are:

* You are using the newer nvidia-docker2 plugin, whereas this project was created for the much older nvidia-docker version 1 plugin which is now deprecated. Good news - you don't need nvidia-docker-compose at all, because the native Docker Compose works directly with nvidia-docker2. See the nvidia-docker2 documentation for information about this.

* You are using the native GPU support in Docker, which is even newer than the nvidia-docker2 plugin (even that is now deprecated!). Unfortunately Docker Compose does not have support for that yet (see [compose issue 6691](https://github.com/docker/compose/issues/6691)). But this project cannot help you with that.
